#!/bin/bash

pid=$(ps -eo pid,cmd | grep "mrouted.*-c /tmp/mrouted-$1$"| grep -v grep| awk '{print $1}')
if [ $pid ]; then
	shift
	sudo nsenter -n -m -t $pid "$@"
else
	echo "No such mrouted on net$1"
fi


